apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - name: hello-python
          image: rorisang/hello-python:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
